name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef86eaf103e744ccd2a679167e433b160a5cb967373e9dbfcebb8a28d4705d54"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
