name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1d6742e1fde23dd3526fb28db49792884ecb02e67a1d6ce2e432722cb9ce637"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
